# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

complementos :
  apto :
    paquetes :
      - libwebp-dev
      - libpoppler-cpp-dev
      - datos poppler
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
